In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from cipher import Ring, Parameters, Context 
from scheme import Evaluator, Encryptor, Decryptor

In [4]:
myring = Ring(seed=1234)
parms = Parameters(logp = 30, logq = 150, logn = 12)
context = Context(parms, myring)

sk = context.generate_secret_key()

In [5]:
context.params

 logp: 30
 logq: 150 
 logn: 12

In [18]:
keys = {"mult":'hihi',
        "rot":{'1':'hi1',
               '2':'hi2',
               '4':'hi4',
               '8':'hi8'}}

evalu = Evaluator(keys)
encryptor = Encryptor(context)

decryptor = Decryptor(sk)

ctxt = encryptor.encrypt(np.array([1,2,3,4,5,6,7,8]))

In [7]:
ctxt

You can't read the content

In [8]:
# you need to decrypt ctxt to view the data
decrypted = decryptor.decrypt(ctxt)

In [26]:
ctxt1 = encryptor.encrypt([1,2,3,4])
ctxt2 = encryptor.encrypt([4,5,6,7])

print(decryptor.decrypt(ctxt1))
print(decryptor.decrypt(ctxt2))

new_ctxt = evalu.add(ctxt1, ctxt2, inplace=False)

[1 2 3 4]
[4 5 6 7]


In [24]:
new_ctxt._arr

array([13, 17, 21, 25])

In [42]:
from ciphertext import CiphertextStat

In [46]:
ctxt = CiphertextStat(30, 120, 12)

## Wrong SK

In [25]:
another_sk = sk +1
wrong_decryptor = Decryptor(another_sk)

wrong_decryptor.decrypt(ctxt)

ValueError: You have a wrong secret key

## ctxt as a return

In [17]:
ctxt1 = encryptor.encrypt([1,2,3,4])

ctxt2 = encryptor.encrypt([4,5,6,7])

In [19]:
evalu.add(ctxt1, ctxt2, inplace=True)

ValueError: too many values to unpack (expected 2)