In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
from cipher import Ring, Parameters, Context 
from scheme import Evaluator, Encryptor, Decryptor

## Test configuration

In [3]:
abs_tol = 1e-5 # error tolerance

## Context set up

In [4]:
myring = Ring(seed=1234)
parms = Parameters(logp = 30, logq = 150, logn = 12)
context = Context(parms, myring)

sk = context.generate_secret_key()

print(context.params)

 logp: 30
 logq: 150 
 logn: 12


## Create Agents

In [5]:
keys = {"mult":context.generate_mult_key(),
        "rot":{'1':'hi1',
               '2':'hi2',
               '4':'hi4',
               '8':'hi8'}}

ev = Evaluator(keys)
encryptor = Encryptor(context)

decryptor = Decryptor(sk)

## Create a ctxt and attempt to print it 
Both ndarray and list are OK

In [6]:
ctxt1 = encryptor.encrypt(np.array([1,2,3,4]))
ctxt2 = encryptor.encrypt([2,3,3,5])
print(ctxt1)

You can't read the content


#### You need to first decrypt it

In [23]:
decrypted = decryptor.decrypt(ctxt2)
print(decrypted)

[2. 3. 3. ... 0. 0. 0.]


## Addition

In [24]:
new_ctxt = ev.add(ctxt1, ctxt2, inplace=False)

print(decryptor.decrypt(new_ctxt))

[3. 5. 6. ... 0. 0. 0.]


### Mult

In [25]:
ctxt3 = ev.mult(ctxt1, ctxt2, inplace=False)

print(decryptor.decrypt(ctxt3))

evalu.mult(ctxt1, ctxt2, inplace=True)
print(decryptor.decrypt(ctxt1))

[2. 6. 9. ... 0. 0. 0.]
[2. 6. 9. ... 0. 0. 0.]


### mult by plain

ptxt can be a
1. scalar
2. single-element sequence 
3. n_element-long sequence
4. nslots-long sequence

In [ ]:
ev.mult_by_plain(ctxt1, 5, inplace=True)

print(decryptor.decrypt(ctxt1))

## Algorithms
### sum

In [26]:
from algorithms import Algorithms 
algo = Algorithms(ev)

summed = algo.fhe_sum(ctxt1, partial=False)

_dec = decryptor.decrypt(summed) # if partial=True, only the first slot if valid.
assert np.isclose(np.sum(ctxt1._arr), _dec[0], atol=abs_tol), "Error!"