In [1]:
%load_ext autoreload
%autoreload 2

_n_elements보다는 tile tensor처럼 {'stride':1, 'begin':-8, 'end': 8} 이런 식이 좋을 듯. 

In [2]:
import numpy as np
from cipher import *
from scheme import *

from algorithms import Algorithms 
from stats import Statistics

In [3]:
myring = Ring(seed=1234)
parms = Parameters(logp = 30, logq = 150, logn = 12)
nslots = 2**parms.logn
context = Context(parms, myring)

sk = context.generate_secret_key()

print(context.params)

 logp: 30
 logq: 150 
 logn: 12


In [4]:
keys = {"mult":context.generate_mult_key(),
        "rot":{'1':'hi1',
               '2':'hi2',
               '4':'hi4',
               '8':'hi8'}}
ev = Evaluator(keys) # Evaluator도 그냥 context만 넣게 할까? 
encryptor = Encryptor(context)

decryptor = Decryptor(sk)

arr = np.array([1,2,3,4,5,6,7,8])

ctxt = encryptor.encrypt(arr)

In [20]:
algo = Algorithms(ev)

st = Statistics(algo, ev)

check = Checker()

### variance

In [21]:
arr = np.array([1,2,3,4,5,6,7,8])

ctxt = encryptor.encrypt(arr)
var = st.variance(ctxt)

check.close(var._arr[0], np.var(arr))

Absolute error within: 1.0E-06
Relative error within: 1.0E-04


### Covariance

In [22]:
arr1 = np.array([1,6,3,2,4,6,8,2])
arr2 = np.arange(3,11)

ctxt1 = encryptor.encrypt(arr1)
ctxt2 = encryptor.encrypt(arr2)
cov = st.cov(ctxt1, ctxt2)

check.close(cov._arr[0], np.cov(arr1, arr2)[0,1])

Absolute error within: 1.0E-06
Relative error within: 1.0E-04


In [23]:
np.cov(arr1, arr2)

array([[6., 2.],
       [2., 6.]])

### Coeffcient of variance

In [36]:
result = st.coef_var(ctxt)

check.close(result._arr[0], np.var(arr) / np.mean(arr))

Absolute error within: 1.0E-06
Relative error within: 1.0E-04


## Correleation Coefficient

In [22]:
np.correlate(arr1, arr2)

array([222])

In [27]:
np.corrcoef(arr1, arr2)

array([[1.        , 0.33333333],
       [0.33333333, 1.        ]])